
// Swift file generated by alphabet-lookup.rb
// Do not edit this generated content directly
import Foundation

public enum Base32DictionaryEntry {
    case Whitespace
    case Padding
    case Invalid
    case Typo(UInt8)
    case Valid(UInt8)
}

public let Base32LookupDictionary:[Base32DictionaryEntry] = [
.Invalid,    .Invalid,    .Invalid,    .Invalid,    .Invalid,    .Invalid,    .Invalid,    .Invalid,    
.Invalid,    .Whitespace, .Whitespace, .Invalid,    .Invalid,    .Whitespace, .Invalid,    .Invalid,    
.Invalid,    .Invalid,    .Invalid,    .Invalid,    .Invalid,    .Invalid,    .Invalid,    .Invalid,    
.Invalid,    .Invalid,    .Invalid,    .Invalid,    .Invalid,    .Invalid,    .Invalid,    .Invalid,    
.Whitespace, .Invalid,    .Invalid,    .Invalid,    .Invalid,    .Invalid,    .Invalid,    .Invalid,    
.Invalid,    .Invalid,    .Invalid,    .Invalid,    .Invalid,    .Invalid,    .Invalid,    .Invalid,    
.Invalid,    .Typo(11),   .Valid(26),  .Valid(27),  .Valid(28),  .Valid(29),  .Valid(30),  .Valid(31),  
.Typo( 1),   .Invalid,    .Invalid,    .Invalid,    .Invalid,    .Padding,    .Invalid,    .Invalid,    
.Invalid,    .Valid( 0),  .Valid( 1),  .Valid( 2),  .Valid( 3),  .Valid( 4),  .Valid( 5),  .Valid( 6),  
.Valid( 7),  .Valid( 8),  .Valid( 9),  .Valid(10),  .Valid(11),  .Valid(12),  .Valid(13),  .Valid(14),  
.Valid(15),  .Valid(16),  .Valid(17),  .Valid(18),  .Valid(19),  .Valid(20),  .Valid(21),  .Valid(22),  
.Valid(23),  .Valid(24),  .Valid(25),  .Invalid,    .Invalid,    .Invalid,    .Invalid,    .Invalid,    
.Invalid,    .Valid( 0),  .Valid( 1),  .Valid( 2),  .Valid( 3),  .Valid( 4),  .Valid( 5),  .Valid( 6),  
.Valid( 7),  .Valid( 8),  .Valid( 9),  .Valid(10),  .Valid(11),  .Valid(12),  .Valid(13),  .Valid(14),  
.Valid(15),  .Valid(16),  .Valid(17),  .Valid(18),  .Valid(19),  .Valid(20),  .Valid(21),  .Valid(22),  
.Valid(23),  .Valid(24),  .Valid(25),  .Invalid,    .Invalid,    .Invalid,    .Invalid,    .Invalid,    
]
